maybe its working

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,19 +28,22 @@ runs:
         mv ${{inputs.public-assets-dir}} .tmp && echo "Deu bom b"
         git fetch
         git checkout ${{inputs.gh-pages-source-branch}} && echo "Deu bom c"
-        mkdir ${{inputs.output-dir}} || echo "Creating dir ${{inputs.output-dir}} can fail safely"
+        mkdir ${{inputs.output-dir}} || echo "Creating dir '${{inputs.output-dir}}' can fail safely"
         rm -r ${{inputs.output-dir}}/$BRANCH_NAME && echo "Deu bom d"
         mv .tmp ${{inputs.output-dir}}/$BRANCH_NAME && echo "Deu bom e"
-        git status
+        git status && echo "Deu bom f"
+        echo "--------------------"
         git status | grep ${{inputs.output-dir}}
         if [ #? -eq 0 ]; then
           echo "GREP?"
           git add ${{inputs.output-dir}}/$BRANCH_NAME
           git commit -m "[skip ci]  ref to ${{github.event.head_commit.id}}"
         fi
+        echo "Finish"
       shell: bash
     - name: 'Try to push with updated review app'
       run: |
+        echo "-----------"
         counter=0
         function retry() {
           echo "Retry to push until succeeds, just in case there another push just happened"
